#!/usr/bin/env node
// Fetches D&D 5e data from dnd5eapi.co and saves to dnd_db/en/
// Also builds browser bundles (window.DND_SPELLS_EN, window.DND_MONSTERS_EN)
// Run: node scripts/fetch_all.js

const fs   = require('fs');
const path = require('path');
const { ft, ftSpeed, ftSenses } = require('./units');

const BASE = 'https://www.dnd5eapi.co';
const API  = `${BASE}/api/2014`;
const ROOT = path.join(__dirname, '..');
const EN   = path.join(ROOT, 'dnd_db', 'en');

const sleep = ms => new Promise(r => setTimeout(r, ms));

async function get(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`HTTP ${r.status}: ${url}`);
  return r.json();
}

// ── SPELLS ──────────────────────────────────────────────────────────────────

async function fetchSpells() {
  const dir = path.join(EN, 'dnd_spells');
  fs.mkdirSync(dir, { recursive: true });

  process.stdout.write('📖 Spell index... ');
  const index = await get(`${API}/spells`);
  fs.writeFileSync(path.join(dir, '_index.json'), JSON.stringify(index, null, 2));
  console.log(`${index.count} sorts`);

  const spells = [];
  for (let i = 0; i < index.results.length; i++) {
    const item = index.results[i];
    process.stdout.write(`\r  ✨ ${String(i+1).padStart(3)}/${index.results.length}  ${item.index.padEnd(40)}`);
    try {
      const s = await get(`${BASE}${item.url}`);
      fs.writeFileSync(path.join(dir, `${item.index}.json`), JSON.stringify(s, null, 2));
      spells.push(s);
    } catch(e) {
      console.error(`\n  ⚠ ${item.index}: ${e.message}`);
    }
    if (i % 25 === 24) await sleep(300);
  }
  console.log(`\n  ✅ ${spells.length} sorts sauvegardés`);

  // Build bundle
  const bundle = spells.map(s => ({
    index:         s.index,
    name:          s.name,
    level:         s.level,
    school:        s.school?.name || '',
    casting_time:  s.casting_time || '',
    range:         ft(s.range || ''),
    duration:      ft(s.duration || ''),
    concentration: !!s.concentration,
    ritual:        !!s.ritual,
    components:    s.components || [],
    material:      ft(s.material || ''),
    classes:       (s.classes || []).map(c => c.name),
    desc:          ft((s.desc || []).join('\n')),
    higher_level:  ft((s.higher_level || []).join('\n')),
    attack_type:   s.attack_type || '',
    damage:        s.damage ? {
      damage_type:               s.damage.damage_type?.name || '',
      damage_at_slot_level:      s.damage.damage_at_slot_level || {},
      damage_at_character_level: s.damage.damage_at_character_level || {},
    } : null,
    dc: s.dc ? { dc_type: s.dc.dc_type?.name || '', dc_success: s.dc.dc_success || '' } : null,
    area_of_effect: s.area_of_effect || null,
  }));

  fs.writeFileSync(
    path.join(ROOT, 'dnd_db', 'bundle_spells_en.js'),
    `/* D&D 5e Spells — English — generated by scripts/fetch_all.js */\nwindow.DND_SPELLS_EN=${JSON.stringify(bundle)};`
  );
  console.log('  📦 dnd_db/bundle_spells_en.js');
  return spells;
}

// ── MONSTERS ─────────────────────────────────────────────────────────────────

async function fetchMonsters() {
  const dir = path.join(EN, 'dnd_monsters');
  fs.mkdirSync(dir, { recursive: true });

  process.stdout.write('🐉 Monster index... ');
  const index = await get(`${API}/monsters`);
  fs.writeFileSync(path.join(dir, '_index.json'), JSON.stringify(index, null, 2));
  console.log(`${index.count} monstres`);

  const monsters = [];
  for (let i = 0; i < index.results.length; i++) {
    const item = index.results[i];
    process.stdout.write(`\r  👾 ${String(i+1).padStart(3)}/${index.results.length}  ${item.index.padEnd(40)}`);
    try {
      const m = await get(`${BASE}${item.url}`);
      fs.writeFileSync(path.join(dir, `${item.index}.json`), JSON.stringify(m, null, 2));
      monsters.push(m);
    } catch(e) {
      console.error(`\n  ⚠ ${item.index}: ${e.message}`);
    }
    if (i % 25 === 24) await sleep(300);
  }
  console.log(`\n  ✅ ${monsters.length} monstres sauvegardés`);

  const bundle = monsters.map(m => {
    // armor_class can be array or number depending on API version
    const ac = Array.isArray(m.armor_class)
      ? (m.armor_class[0]?.value ?? 10)
      : (m.armor_class ?? 10);
    return {
      index:                m.index,
      name:                 m.name,
      size:                 m.size || '',
      type:                 m.type || '',
      subtype:              m.subtype || '',
      alignment:            m.alignment || '',
      armor_class:          ac,
      armor_desc:           Array.isArray(m.armor_class) ? (m.armor_class[0]?.desc || '') : '',
      hit_points:           m.hit_points || 0,
      hit_dice:             m.hit_dice || '',
      speed:                ftSpeed(m.speed || {}),
      strength:             m.strength || 10,
      dexterity:            m.dexterity || 10,
      constitution:         m.constitution || 10,
      intelligence:         m.intelligence || 10,
      wisdom:               m.wisdom || 10,
      charisma:             m.charisma || 10,
      proficiencies:        (m.proficiencies || []).map(p => ({
        value: p.value, name: p.proficiency?.name || ''
      })),
      damage_vulnerabilities: m.damage_vulnerabilities || [],
      damage_resistances:     m.damage_resistances || [],
      damage_immunities:      m.damage_immunities || [],
      condition_immunities:   (m.condition_immunities || []).map(c => c.name || c),
      senses:               ftSenses(m.senses || {}),
      languages:            m.languages || '',
      challenge_rating:     m.challenge_rating ?? 0,
      xp:                   m.xp || 0,
      proficiency_bonus:    m.proficiency_bonus || 2,
      special_abilities:    (m.special_abilities || []).map(a => ({ name: a.name, desc: ft(a.desc || '') })),
      actions:              (m.actions || []).map(a => ({
        name: a.name, desc: ft(a.desc || ''),
        attack_bonus: a.attack_bonus,
        damage: a.damage
      })),
      reactions:            (m.reactions || []).map(a => ({ name: a.name, desc: ft(a.desc || '') })),
      legendary_desc:       ft(m.legendary_desc || ''),
      legendary_actions:    (m.legendary_actions || []).map(a => ({ name: a.name, desc: ft(a.desc || '') })),
    };
  });

  fs.writeFileSync(
    path.join(ROOT, 'dnd_db', 'bundle_monsters_en.js'),
    `/* D&D 5e Monsters — English — generated by scripts/fetch_all.js */\nwindow.DND_MONSTERS_EN=${JSON.stringify(bundle)};`
  );
  console.log('  📦 dnd_db/bundle_monsters_en.js');
  return monsters;
}

// ── MAIN ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log('╔══════════════════════════════════════╗');
  console.log('║   D&D 5e Data Fetcher  (Anglais)     ║');
  console.log('╚══════════════════════════════════════╝\n');

  await fetchSpells();
  console.log();
  await fetchMonsters();

  console.log('\n╔══════════════════════════════════════╗');
  console.log('║  Terminé !                           ║');
  console.log('║  Prochaine étape :                   ║');
  console.log('║    node scripts/translate_fr.js      ║');
  console.log('╚══════════════════════════════════════╝');
}

main().catch(e => { console.error('\n❌', e.message); process.exit(1); });
