#!/usr/bin/env node
// ============================================================
//  build_portable.js — génère portable_template.js
//  Usage: node scripts/build_portable.js
//         (depuis le dossier dnd5e-sheets/)
// ============================================================
'use strict';
const fs   = require('fs');
const path = require('path');

const ROOT   = path.join(__dirname, '..');
const DB_DIR = path.join(ROOT, '..', 'dnd_db');

function read(rel) {
  const p = path.join(ROOT, rel);
  if (!fs.existsSync(p)) { console.warn('⚠  Manquant:', p); return ''; }
  return fs.readFileSync(p, 'utf8');
}
function readAbs(p) {
  if (!fs.existsSync(p)) return '';
  return fs.readFileSync(p, 'utf8');
}

// ── Sources ──────────────────────────────────────────────────
let html        = read('sheet.html');
const css       = read('shared/style.css');
const appJs     = read('shared/app.js');
const spellJs   = read('shared/spell_browser.js');

// ── dnd_db bundles (skip monsters — DM screen only) ──────────
const BUNDLES = [
  'bundle_spells_en.js',
  'bundle_spells_fr.js',
  'bundle_classes_en.js',
  'bundle_classes_fr.js',
  'bundle_races_en.js',
  'bundle_races_fr.js',
  'bundle_backgrounds_en.js',
  'bundle_backgrounds_fr.js',
  'bundle_feats_en.js',
  'bundle_feats_fr.js',
];
let bundleSrc = '';
console.log('Bundles dnd_db :');
for (const b of BUNDLES) {
  const src = readAbs(path.join(DB_DIR, b));
  if (src) {
    bundleSrc += src + '\n';
    console.log('  ✓', b, `(${Math.round(src.length / 1024)} KB)`);
  } else {
    console.log('  –', b, '(absent, ignoré)');
  }
}

// ── Inline CSS ───────────────────────────────────────────────
html = html.replace(
  '<link rel="stylesheet" href="shared/style.css">',
  `<style>\n${css}\n</style>`
);

// ── Supprimer les <script src> des bundles et de portable_template
html = html.replace(/<script src="\.\.\/dnd_db\/[^"]+\.js"[^>]*><\/script>\n?/g, '');
html = html.replace(/<script src="portable_template\.js"[^>]*><\/script>\n?/g, '');

// ── Inline SortableJS via CDN (on garde le tag CDN tel quel)

// ── Inline bundles + spell_browser.js ────────────────────────
html = html.replace(
  '<script src="shared/spell_browser.js"></script>',
  `<script>\n${bundleSrc}\n</script>\n<script>\n${spellJs}\n</script>`
);

// ── Inline app.js ─────────────────────────────────────────────
html = html.replace(
  '<script src="shared/app.js"></script>',
  `<script>\n${appJs}\n</script>`
);

// ── Remplacer DND.init() par le bootstrap portable ───────────
html = html.replace(
  '<script>DND.init();</script>',
  `<script>(function(){
  const data = window.__PORTABLE_DATA__;
  const body   = document.getElementById('sheet-body');
  const notice = document.getElementById('no-char-notice');
  if (!data) { if (notice) notice.style.display = 'flex'; return; }
  DND.storageKey = 'dnd5e_char___portable__';
  localStorage.setItem(DND.storageKey, JSON.stringify(data));
  if (body) body.style.display = '';
  DND.load(); DND.bindAll(); DND.recalcAll(); DND.initSortablePanels();
  DND.showMobileTab(localStorage.getItem('_mtab_' + DND.storageKey) || 'tab-combat');
  window.addEventListener('resize', () => {
    if (window.innerWidth > 768) {
      document.querySelectorAll('.panel[data-tab]').forEach(el => { el.style.display = ''; });
      const sp = document.getElementById('spell-panel');
      if (sp && !DND._isSpellcaster) sp.style.display = 'none';
    } else { DND.showMobileTab(DND._mobileTab); }
  }, { passive: true });
})();
</script>`
);

// ── Injecter le placeholder de données avant </body> ─────────
html = html.replace(
  '</body>',
  `<script>window.__PORTABLE_DATA__ = /*__CHAR_DATA__*/null;</script>\n</body>`
);

// ── Écrire portable_template.js ──────────────────────────────
const outPath = path.join(ROOT, 'portable_template.js');
const output  = `// Auto-generated by scripts/build_portable.js — NE PAS ÉDITER
// Pour régénérer : node scripts/build_portable.js (depuis dnd5e-sheets/)
window.__PORTABLE_TEMPLATE__ = ${JSON.stringify(html)};
`;

fs.writeFileSync(outPath, output, 'utf8');
const sizeKB = Math.round(fs.statSync(outPath).size / 1024);
console.log(`\n✓  portable_template.js généré (${sizeKB} KB)`);
if (sizeKB > 8000) {
  console.warn(`⚠  Fichier > 8 MB — Discord limitera l'envoi direct`);
} else {
  console.log(`   Export portable estimé < ${sizeKB} KB — Discord OK ✓`);
}
